### ISSUE TITLE
chiseled bookshelf redstone broken

### ISSUE THREAD

**Issue by cosmoderp** [1mphuls3/Biome-Backport#10]
So empty and just placed it produces no signal.  you fill it with with books it fills to 6 which is fine but when you dont remove them in the order they were place you are left with a signal of 3.  furthermore if you do remove them in the correct order you are left with a signal of 1.  It never returns back to no signal when its empty.

I am on 1.19.2

**Comment by 1mphuls3** [comment]
The signal never goes back to 0 in vanilla Minecraft either. The order of the books doesn't matter, it's the slot number that defines the signal. The slots go from right to left, then top to bottom like this:

1 2 3
4 5 6

The slot you interact with (add or remove a book) defines the signal strength. This is how it works in the 1.20 snapshots currently. From what I can see, it works exactly the same as it does in vanilla Minecraft.

**Comment by 1mphuls3** [comment]
Closing for now
