### ISSUE TITLE
Unable to load this mod on the server in 1.19.2

### ISSUE THREAD

**Issue by LrbsX** [1mphuls3/Biome-Backport#13]
see the log
[latest.log](https://github.com/1mphuls3/Biome-Backport/files/12330895/latest.log)
help me, plz!

**Comment by Kupperu** [comment]
Are there any update on this? My suspicion is its a client-side mod but that doesn't make sense.

**Comment by 1mphuls3** [comment]
It looks like the Screen for the hanging sign is being loaded on the server even though screens are only client-side. I'm looking into it now.

**Comment by 1mphuls3** [comment]
Should be fixed, just awaiting CF approval.
