### ISSUE TITLE
The bees attached to the tree, or the leafcutter ant from Alex's Mobs, or any mob that seems to have similar patterns to bee Spawns massively everytime I break the Block

### ISSUE THREAD

**Issue by Kooreh** [1mphuls3/Biome-Backport#14]
I'll leave the Link to the youtube video that shows exactly what I am talking about : https://www.youtube.com/watch?v=uavvuFAalbY&ab_channel=JYH

basically, for some odd reason, it seems that everytime I try to break or interact with the items or blocks included in the mod, it creates these massive amount of entities to spawn; I don't think it's also exclusive to bees only, I had a mod called 'Alex's Mobs' installed on as well and one of the mob that kind of works similar to Bee was Leafcutter Ant, since they also go inside the block called 'leafcutter anthill'; anyway, any mobs that has their 'hive' seems to be having this crazy glitch. please help!

**Comment by 1mphuls3** [comment]
This only happens when you break stuff in this mod and not other blocks? Can you send a mod list so I can check if it's an incompatibility? I honestly don't even know where to start looking for causes for this issue because I don't change hive blocks behavior.

**Comment by 1mphuls3** [comment]
I checked and this doesn't happen when I break a block with the mod by itself. So it's either another mod causing the issue or some specific circumstances that cause this to happen.
