### ISSUE TITLE
[Suggestion] Config Option to Disable Biome Generation

### ISSUE THREAD

**Issue by Desymoo** [1mphuls3/Biome-Backport#5]
As the title suggests :) The biome itself seems to conflict with the natural generation of a few other worldgen mods but I'd really love to keep the new blocks and cherry trees, they work great!

**Comment by 1mphuls3** [comment]
What sorts of conflicts are there? I'd love to fix that, especially since the biome is a major part of the mod. I'll see if I can add a config option sometime soon as well.

**Comment by 1mphuls3** [comment]
Config should be working in version 1.1.4 when it gets approved on Curseforge!
